[phases.setup]
nixPkgs = ["php", "composer", "mysql"]

[phases.install]
cmds = ["composer install --ignore-platform-reqs --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "ls -la",
  "pwd",
  "[ -f artisan ] && echo 'artisan found' || (echo 'artisan NOT found' && exit 1)",
  "chmod +x start.sh"
]

[start]
cmd = "./start.sh" 