[phases.setup]
nixPkgs = ["php", "composer", "mysql"]

[phases.install]
cmds = ["composer install --ignore-platform-reqs --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "ls -la",
  "pwd",
  "chmod +x start.sh"
]

[start]
cmd = "./start.sh" 