[build]
builder = "nixpacks"
watchPatterns = ["Backend/**/*"]

[deploy]
startCommand = "cd Backend && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure" 